name: CI / Automated testing

on:
  workflow_dispatch:

  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEPENDENCIES_CACHE: swift-cache
  NX_CACHE: nx-cache

jobs:
  build-and-verify:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Resolve deps and build
        uses: ./.github/workflows/composite/swift
        with:
          cache: ${{ env.DEPENDENCIES_CACHE }}

      - name: Lint code
        run: make lint

      - name: Formatting issues
        run: make format
